# Generated by Django 4.2.23 on 2025-06-24 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('account_status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'SUSPENDED'), (3, 'TERMINATED')], default=payments.models.AccountStatus['ACTIVE'])),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'INTERNET'), (2, 'MOBILE'), (3, 'ONE_OFF'), (4, 'TV')])),
                ('base_price', models.FloatField()),
                ('is_recurring', models.BooleanField()),
                ('billing_cycle', models.IntegerField(blank=True, choices=[(1, 'MONTHLY'), (2, 'YEARLY')], null=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'CANCELED'), (3, 'EXPIRED'), (4, 'AWAITING_ACTIVATION')], default=payments.models.PurchaseStatus['ACTIVE'])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payments.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payments.service')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.IntegerField(choices=[(1, 'EUR'), (2, 'BGN'), (3, 'USD'), (4, 'GBP')], default=payments.models.Currency['BGN'])),
                ('payment_method', models.IntegerField(choices=[(1, 'CREDIT_CARD'), (2, 'BANK_TRANSFER'), (3, 'MOBILE_PAYMENT'), (4, 'CASH_PAYMENT')])),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'REFUNDED')], default=payments.models.PaymentStatus['PENDING'])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.customer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.purchase')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
